### ISSUE TITLE
conversion sample audio

### ISSUE THREAD

**Issue by fanpengustc** [patrickltobing/cyclevae-vc#1]
where is the conversion  sample，can not find the directory trained_example

**Comment by patrickltobing** [comment]
sorry, I misexplained in the readme,

please open the link of the [trained_example](http://bit.ly/309zWXc) as in the readme,

then
`$ cd cyclevae-vc_trained/egs/one-to-one/`

for a trained model using batch utterance size = 1, then,
`$ cd exp/tr50_22.05k_cyclevae_gauss_VCC2SF1-VCC2TF1_hl1_hu1024_ld32_ks3_ds2_cyc2_lr1e-4_bs80_wd0.0_do0.5_epoch500_bsu1_bsue1/`

the audios are located in 'wav_cv_...'

**Comment by fanpengustc** [comment]
Thanks for your answer！


发自我的 iPhone
