### ISSUE TITLE
Where could I find the bash script to extract speaker features which are in conf folder?

### ISSUE THREAD

**Issue by v-manhlt3** [patrickltobing/cyclevae-vc#3]
Hi Patrick,

First of all, thank you for your brilliant work. I am working on my research paper and I am planning to use your work as a baseline, however, I would like to estimate model's performance on VCTK dataset. I could not find any python files or bash script files to generate speaker's configs as in "conf" folder. Therefore, I appreciate if you can help me to generate speaker's conf.

**Comment by patrickltobing** [comment]
Hi, thanks for the request.

The development related on this repo has been moved to [cyclevae-vc-neuralvoco](https://github.com/patrickltobing/cyclevae-vc-neuralvoco).

> I could not find any python files or bash script files to generate speaker's configs as in "conf" folder. 

Please checkout the directory [cycvae_mwdlp_vcc20](https://github.com/patrickltobing/cyclevae-vc-neuralvoco/tree/master/egs/cycvae_mwdlp_vcc20).

Follow **Data preparation** step and **Data preprocessing** steps until `stage=0init`.

All *.f0 and *.pow files will then be located in the conf folder, and will be written to `conf/spkr.yml`

Let me know if there are any troubles.

**Comment by v-manhlt3** [comment]
Thanks for your response, now I can train your model on my dataset. However, it seems to take a very long time to finish training with only 4 speakers. 
So, I am curious that how long does it take to finish training on the VCC2020 dataset?

**Comment by patrickltobing** [comment]
> However, it seems to take a very long time to finish training with only 4 speakers.
> how long does it take to finish training on the VCC2020 dataset?

If you are asking about the training time for the github project on the link I sent above, I have put it on the readme.
It may take 2 days for first VC training of vcc20 set.

If you are asking for this github project, I kind of forgot, it might take 3 days or so.

**Comment by v-manhlt3** [comment]
Thanks for your support!!!
